module.exports = [
    {
        pokedex: "001",
        name: "Bulbasaur",
        type: ["GRASS", "POISON"],
        total: 50,
        hp: 55,
        attack: 6,
        attackHeavy: 0,
        Cool: 610,
        Range: 500,
        Sight: 700,
        defense: 0,
        Speed: 225,
        image: "bulbasaur.png",
        klass: "gunner",
        armor: 'light',
        bulletName: 'effect_bulleta_idle'
    },
    {
        pokedex: "002",
        name: "Ivysaur",
        type: ["GRASS", "POISON"],
        total: 125,
        hp: 125,
        attack: 10,
        attackHeavy: 10,
        Cool: 1070,
        Range: 600,
        Sight: 800,
        defense: 1,
        Speed: 225,
        image: "ivysaur.png",
        klass: "gunner",
        armor: 'heavy',
        bulletName: 'effect_bulletb_idle'
    },
    {
        pokedex: "003",
        name: "Venusaur",
        type: ["GRASS", "POISON"],
        total: 125,
        hp: 60,
        attack: 2,
        Cool: 200,
        Range: 600,
        Sight: 1200,
        defense: 1,
        Speed: 225,
        image: "venusaur.png",
        klass: "healer",
        armor: 'light'
    },
    {
        pokedex: "004",
        name: "Blastoise",
        type: ["GRASS", "POISON"],
        total: 75,
        hp: 75,
        attack: 10,
        attackLight: 15,
        Cool: 1690,
        Range: 600,
        Sight: 800,
        defense: 1,
        Speed: 425,
        image: "blastoise.png",
        klass: "gunner",
        armor: 'light',
        bulletName: 'effect_bulletd_idle'
    },
    {
        pokedex: "005",
        name: "Charmander",
        type: ["FIRE"],
        total: 200,
        hp: 175,
        attack: 15,
        attackHeavy: 10,
        Cool: 740,
        Range: 900,
        Sight: 1000,
        defense: 1,
        Speed: 315,
        image: "charmander.png",
        klass: "siege",
        armor: 'heavy',
        bulletName: 'effect_bullete_idle',
        SplashRange: 300
    },
    {
        pokedex: "006",
        name: "Charmeleon",
        type: ["FIRE"],
        total: 375,
        hp: 400,
        attack: 30,
        Cool: 1280,
        Range: 700,
        Sight: 800,
        defense: 1,
        Speed: 180,
        image: "charmeleon.png",
        klass: "dual",
        armor: 'heavy',
        bulletName: 'effect_bullete_idle'
    }
];
